### ISSUE TITLE
Need better error handling

### ISSUE THREAD

**Issue by gowthamrao** [anthonysena/lsc#12]
**Describe the bug**
Cohort is empty
Empty cohorts being compared

**To Reproduce**
1. Go to 'compare cohort charcterization'
2. Click on 'select one or more cohorts with 0 record count'

**Expected behavior**

**Additional context**

**Comment by gowthamrao** [comment]
https://github.com/anthonysena/lsc/issues/11

**Comment by anthonysena** [comment]
Closing to track this via #11
