### ISSUE TITLE
make all tables allow to select # records/screen

### ISSUE THREAD

**Issue by pbr6cornell** [anthonysena/lsc#6]
Currently, tables in Cohort Counts and Cohort Characterization default to showing 10 rows/screen, and then you have to click 'next page' to work your way through the results.   Compare Cohort Char tables have dropdown to select # rows/screen, which allow you to change it to 25/50/100/-1. 

All tables should allow dropdown to select the # of records to display.  Default = 25 would be preferred.

**Comment by anthonysena** [comment]
This is now added - the new data table allow for the # rows/screen but it is located at the bottom of the table.
